Add socket io configuration docs
sematic-ai/helm-charts pull request #8
Opened 2023-02-02 23:48 UTC by snoshy

Add socket io configuration docs

2023-02-02 23:51 UTC, tscurtu commented on README.md
> +| `deployment.worker_count`                                 | Number of WSGI workers per Sematic server pod (API only)      | `1`                                     |
Please mention that the `socketio.dedicated` configuration must also be enabled if increasing this.

2023-02-03 00:20 UTC, augray approved these changes

2023-02-03 17:14 UTC, tscurtu requested changes

2023-02-03 17:14 UTC, tscurtu commented on README.md
> +| `deployment.socket_io.address`                            | Cluster-private URL to reach dedicated Socket I/O server      | Not set                                 |
This was removed from the values definitions. Please remove this doc entry as well.

2023-02-03 20:00 UTC, tscurtu approved these changes
Thank you! :shipit:

2023-02-03 20:00 UTC, merged